# Generated by Django 3.0.3 on 2020-12-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_ex',
            name='genre',
            field=models.CharField(default='romance', max_length=120),
            preserve_default=False,
        ),
    ]
